
name: Self Test

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  summary-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Self Test
        uses: ./. 

